version: "3.8"

services:
  backend:
    container_name: infisical-backend
    image: infisical/infisical:latest-postgres
    pull_policy: always
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8085:8080"
    environment:
      - NODE_ENV=production
      # Optional overrides (can also go in .env)
      - DB_CONNECTION_URI=postgresql://infisical:$(cat /run/secrets/postgres_password)@db:5432/infisical
      - REDIS_URL=redis://redis:6379
      - SITE_URL=http://coiso:8085
      - ENCRYPTION_KEY=$(cat /run/secrets/encryption_key)
      - AUTH_SECRET=$(cat /run/secrets/auth_secret)
    secrets:
      - encryption_key
      - auth_secret  
      - postgres_password
    networks:
      - coiso

  redis:
    image: redis:7-alpine
    container_name: infisical-redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /srv/docker/infisical/redis_data:/data
    networks:
      - coiso

  db:
    image: postgres:15-alpine
    container_name: infisical-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=infisical
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=infisical
    volumes:
      - /srv/docker/infisical/pg_data:/var/lib/postgresql/data
    secrets:
      - postgres_password      
    networks:
      - coiso
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=infisical && psql --username=infisical --list"]
      interval: 10s
      timeout: 5s
      retries: 10

secrets:
  postgres_password:
    file: /srv/docker/infisical/secrets/postgres-password
  encryption_key:
    file: /srv/docker/infisical/secrets/encryption-key
  auth_secret:
    file: /srv/docker/infisical/secrets/auth-secret

networks:
  coiso:
    name: coiso
    external: true