version: "3.8"

services:
  hello-world:
    build: 
      dockerfile: ./Dockerfiles/hello-world/Dockerfile
      cache_from: []
      no_cache: true
    container_name: hello-world
    restart: unless-stopped
    ports:
      - "8088:8080"        
    networks:
      - coiso
  
networks:
  coiso:
    name: coiso
    external: true