services:
  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:10.6
    env_file:
      - /srv/docker/env/nextcloud.env
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    networks:
      - coiso

  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud:latest
    env_file:
      - /srv/docker/env/nextcloud.env
    restart: always
    depends_on:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
    networks:
      - coiso

  nextcloud-harp:
    image: ghcr.io/nextcloud/nextcloud-appapi-harp:release
    container_name: nextcloud-harp
    restart: unless-stopped
    env_file:
      - /srv/docker/env/nextcloud.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/nextcloud/harp/certs:/certs
    ports:
      # Port 8780 is for HTTP communication from Nextcloud to HaRP
      - "8780:8780"
      # Port 8782 is for FRP tunnel used by ExApps to connect to HaRP
      - "8782:8782"
    networks:
      - coiso 

networks:
  coiso:
    name: coiso
    external: true

volumes:
  nextcloud:
  db:
