version: "3.8"

services:
  bitcoind:
    image: bitcoin-core:latest    
    container_name: bitcoind
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - /srv/docker/env/bitcoin.env      
    volumes:
      - /d/srv/docker/bitcoin:/home/bitcoin/.bitcoin
    ports:
      - "8333:8333"         # Bitcoin P2P network
      - "8332:8332"         # RPC
    command:
      - bitcoind
      - -printtoconsole
      - -conf=/home/bitcoin/.bitcoin/bitcoin.conf
      - -datadir=/home/bitcoin/.bitcoin
    networks:
      - coiso
  version: "3.7"

  mempool-web:
    image: mempool/frontend:latest
    env_file:
      - /srv/docker/env/bitcoin.env      
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 80:8080
    networks:
      - coiso     

  mempool-api:
    image: mempool/backend:latest
    env_file:
      - /srv/docker/env/bitcoin.env
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - /srv/docker/mempool/data:/backend/cache
    networks:
      - coiso    

  mempool-db:
    image: mariadb:10.5.21
    env_file:
      - /srv/docker/env/bitcoin.env
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - /srv/docker/mempool/mysql/data:/var/lib/mysql
    networks:
      - coiso

networks:
  coiso:
    name: coiso
    external: true