services:
  openclaw-gateway:
    container_name: openclaw-gateway
    image: ghcr.io/openclaw/openclaw:2026.2.9
    env_file:
      - /srv/docker/env/openclaw.env   
    volumes:
      - /srv/openclaw/config:/home/node/.openclaw
      - /srv/openclaw/workspace:/home/node/.openclaw/workspace
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "lan",
        "--port",
        "18789",
      ]
    networks:
      - coiso

  openclaw-cli:
    container_name: openclaw-cli
    image: ghcr.io/openclaw/openclaw:2026.2.9
    env_file:
      - /srv/docker/env/openclaw.env  
    volumes:
      - /srv/openclaw/config:/home/node/.openclaw
      - /srv/openclaw/workspace:/home/node/.openclaw/workspace
    stdin_open: true
    tty: true
    init: true
    #entrypoint: ["node", "dist/index.js"]
    command: tail -f /dev/null
    networks:
      - coiso

networks:
  coiso:
    name: coiso
    external: true