version: "3.8"

services:
  backend:
    container_name: infisical-backend
    image: infisical/infisical:latest-postgres
    pull_policy: always
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8085:8080"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_URI=postgresql://infisical:${POSTGRES_PASSWORD}@db:5432/infisical
      - REDIS_URL=redis://redis:6379
      - SITE_URL=http://coiso:8085
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
    networks:
      - coiso

  redis:
    image: redis:7-alpine
    container_name: infisical-redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /srv/docker/infisical/redis_data:/data
    networks:
      - coiso

  db:
    image: postgres:15-alpine
    container_name: infisical-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=infisical
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=infisical
    volumes:
      - /srv/docker/infisical/pg_data:/var/lib/postgresql/data
    networks:
      - coiso
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=infisical && psql --username=infisical --list"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  coiso:
    name: coiso
    external: true