version: "3.8"

services:
  bitcoind:
    image: bitcoin-core:latest    
    container_name: bitcoind
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - /srv/docker/env/bitcoin.env      
    volumes:
      - /d/srv/docker/bitcoin:/home/bitcoin/.bitcoin
    ports:
      - "8333:8333"         # Bitcoin P2P network
      - "8332:8332"         # RPC
    command:
      - bitcoind
      - -printtoconsole
      - -conf=/home/bitcoin/.bitcoin/bitcoin.conf
      - -datadir=/home/bitcoin/.bitcoin
    networks:
      - coiso
  
  mempool:
    image: mempool/mempool:latest
    container_name: mempool
    restart: unless-stopped
    depends_on:
      - bitcoind
    env_file:
      - /srv/docker/env/bitcoin.env      
    ports:
      - "4080:80"
    networks:
      - coiso

networks:
  coiso:
    name: coiso
    external: true