version: "3.8"

services:
  bitcoind:
    image: bitcoin-core:latest
    container_name: bitcoind
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - /srv/docker/env/bitcoin.env      
    volumes:
      - /d/srv/docker/bitcoin:/home/bitcoin/.bitcoin
    ports:
      - "8333:8333"         # Bitcoin P2P network
    command:
      - bitcoind
      - -printtoconsole
      - -conf=/home/bitcoin/.bitcoin/bitcoin.conf
      - -datadir=/home/bitcoin/.bitcoin
    networks:
      - coiso
  
  btc-rpc-explorer:
    container_name: btc-rpc-explorer
    image: btc-rpc-explorer:latest
    user: "1000:1000"
    env_file:
      - /srv/docker/env/bitcoin.env    
    networks:
      - coiso  

networks:
  coiso:
    name: coiso
    external: true