version: '3.8'

services:
  mssql-server-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-dev
    hostname: mssql-server-dev-db
    restart: unless-stopped
    ports:
      - "1433:1433"
    env_file:
      - /srv/docker/env/sqlserver.env
    volumes:
      - /srv/docker/sql-server-dev:/var/opt/mssql
    networks:
      - development-server
      
networks:
  development-server:
    name: development-server
    external: true