version: '3.8'
services:
  app:
    container_name: npm_app
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    env_file:
      - /srv/docker/env/npm.env      
    volumes:
      - /srv/docker/npm/data:/data
      - /srv/docker/npm-letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    networks:
      - coiso


  db:
    container_name: npm_db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    env_file:
      - /srv/docker/env/npm.env      
    volumes:
      - /srv/docker/npm-mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - coiso


networks:
  coiso:
    name: coiso
    external: true